/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'bevmo.com',
      instruction: 'Search for "chocolate"',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          searchResults: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                name: { type: 'string' },
                price: { type: 'string' },
              },
              required: ['name', 'price'],
              additionalProperties: false,
            },
            description: 'The first 5 search results with name and price',
          },
        },
        required: ['searchResults'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Searching for "chocolate" as requested.
        await page
          .find('#HeaderSearchField', {
            failover: [
              'header.header > div:nth-of-type(2) > div > predictive-search > main-search > form > div > input',
              'body > div:nth-of-type(2) > sticky-header > header > div:nth-of-type(2) > div > predictive-search > main-search > form > div > input',
            ],
          })
          .inputText('chocolate', { submit: true });

        // Waiting for the search results for "chocolate" to load.
        await page.waitForTimeout(3000);

        // The objective to search for "chocolate" has been completed, as evidenced by the search results page.
        await page.run('markObjectiveComplete', {
          details:
            'Successfully searched for "chocolate" on BevMo.com, which returned 2032 results.',
        });
      },
    },
  ],
};
