/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'www.awaytravel.com',
      instruction: 'Search for "carry-on" and go to the first product page',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          productName: {
            type: 'string',
            description: 'The name of the product',
          },
          price: { type: 'string', description: 'The listed price' },
          description: {
            type: 'string',
            description: 'The product description text',
          },
        },
        required: ['productName', 'price', 'description'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Accepting the cookie consent banner to proceed with the objective.
        await page
          .find(
            '#pandectes-banner > div > div:nth-of-type(2) > button:nth-of-type(2)',
            {
              failover: [
                ".//button[normalize-space(.)='Accept']",
                'div.cc-compliance > button:nth-of-type(2)',
              ],
            },
          )
          .click('left');

        // Clicking the search icon to open the search bar so I can search for "carry-on".
        await page
          .find("(.//button[normalize-space(.)='Search'])[2]", {
            failover: [
              "div:nth-of-type(4) > div > [data-track-click='Nav Link Clicked']",
              'div:nth-of-type(4) > div > [data-track-properties=\'{"location": "Header Nav Secondary", "name": "Search Icon"}\']',
            ],
          })
          .click('left');

        // Typing "carry-on" into the search input and submitting the search.
        await page
          .find('#header-search-input', {
            failover: [
              "[name='q']",
              "[placeholder='Type what you are looking for...']",
            ],
          })
          .inputText('carry-on', { submit: true });

        // Clicking on the first product result for "carry-on" to reach its product page.
        await page
          .find(
            "[href='/products/carry-on-coast-blue?_pos=1&_psq=carry-on&_ss=e&_v=1.0']",
            {
              failover: [
                'li:nth-of-type(1) > div > a.product-tile-search__link',
                'ul.search-drawer__tiles > li:nth-of-type(1) > div > a',
              ],
            },
          )
          .click('left');

        // The objective was to search for 'carry-on' and go to the first product page. I performed the search and clicked the first product result, and I am now on its product page.
        await page.run('markObjectiveComplete', {
          details:
            'I have successfully searched for "carry-on" and navigated to the first product page, which is "The Carry-On" in Coast Blue.',
        });
      },
    },
    {
      pageUrl: 'www.awaytravel.com',
      instruction: 'Search for "carry-on" and go to the first product page',
      schema: {
        $schema: 'https://json-schema.org/draft/2020-12/schema',
        type: 'object',
        properties: {
          productName: {
            type: 'string',
            description: 'The name of the product',
          },
          price: {
            type: 'string',
            description: 'The listed price, including the currency symbol',
          },
          color: { type: 'string', description: 'The color of the product' },
        },
        required: ['productName', 'price', 'color'],
        additionalProperties: false,
      },
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // Accepting cookies to dismiss the banner and access the main site content for searching.
        await page
          .find(
            '#pandectes-banner > div > div:nth-of-type(2) > button:nth-of-type(2)',
            {
              failover: [
                ".//button[normalize-space(.)='Accept']",
                'div.cc-compliance > button:nth-of-type(2)',
              ],
            },
          )
          .click('left');

        // Opening the search bar to search for 'carry-on'.
        await page
          .find("(.//button[normalize-space(.)='Search'])[2]", {
            failover: [
              "div:nth-of-type(4) > div > [data-track-click='Nav Link Clicked']",
              'div:nth-of-type(4) > div > [data-track-properties=\'{"location": "Header Nav Secondary", "name": "Search Icon"}\']',
            ],
          })
          .click('left');

        // Searching for 'carry-on' to find relevant products.
        await page
          .find('#header-search-input', {
            failover: [
              "[name='q']",
              "[placeholder='Type what you are looking for...']",
            ],
          })
          .inputText('carry-on', { submit: true });

        // Clicking on the first product result for 'carry-on' to go to its product page.
        await page
          .find(
            "[href='/products/carry-on-coast-blue?_pos=1&_psq=carry-on&_ss=e&_v=1.0']",
            {
              failover: [
                'li:nth-of-type(1) > div > a.product-tile-search__link',
                'ul.search-drawer__tiles > li:nth-of-type(1) > div > a',
              ],
            },
          )
          .click('left');

        // The objective was to search for "carry-on" and go to the first product page, which has been accomplished.
        await page.run('markObjectiveComplete', {
          details:
            'Successfully searched for "carry-on" and navigated to the product page for "The Carry-On".',
        });
      },
    },
  ],
};
