/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'news.ycombinator.com',
      instruction:
        'Scroll down to find the search box and then do a search for "mac app for web testing". Navigate to the first result.',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // I am scrolling down to find the search box as specified in the overall objective.
        await page.find('html > body', { failover: ['body'] }).scroll('DOWN');

        // I am inputting "mac app for web testing" into the search box to find relevant results as per the objective.
        await page
          .find(
            '#hnmain > tbody > tr:nth-of-type(4) > td > center > form > input',
            { failover: ["[name='q']", 'form > input'] },
          )
          .inputText('mac app for web testing', { submit: true });

        // I am clicking on the first search result to navigate to it as per the objective.
        await page
          .find(
            ".//a[normalize-space(.)='Show HN: Donobu – Mac App for Web Automation and Testing']",
            {
              failover: [
                "div:nth-of-type(1) > [href='https://news.ycombinator.com/item?id=41789633']",
                'div.SearchResults_container > article:nth-of-type(1) > div > div > div:nth-of-type(1) > a:nth-of-type(1)',
              ],
            },
          )
          .click('left');

        // I have completed all steps of the overall objective.
        await page.run('markObjectiveComplete', {
          details:
            'I successfully scrolled down to find the search box, searched for "mac app for web testing", and navigated to the first search result, which is the Hacker News discussion for "Show HN: Donobu – Mac App for Web Automation and Testing".',
        });
      },
    },
  ],
};
