/**
 * @generated
 * This file was generated by Donobu; do not edit manually.
 */
/* eslint-disable */
const { expect } = require('donobu');

module.exports = {
  caches: [
    {
      pageUrl: 'en.wikipedia.org',
      instruction:
        'Search for "artificial intelligence" and navigate to the article',
      schema: null,
      allowedTools: [],
      maxToolCalls: 50,
      run: async ({ page }) => {
        // I am typing "artificial intelligence" into the search bar to find the relevant article as per the objective.
        await page
          .find('#searchInput', {
            failover: [
              "[aria-label='Search Wikipedia']",
              "form > div > div > [title='Search Wikipedia [ctrl-option-f]']",
            ],
          })
          .inputText('artificial intelligence', { submit: true });

        // The current page is the "Artificial intelligence" article on Wikipedia, which was the goal of the search.
        await page.run('markObjectiveComplete', {
          details:
            'I have successfully searched for "artificial intelligence" on Wikipedia and navigated to the corresponding article.',
        });
      },
    },
  ],
};
